### ISSUE TITLE
Feature Request - Glowing Compression Tools

### ISSUE THREAD

**Issue by SirBlazzit** [SirBlobman/Block-Compressor#1]
Would it be possible to create a config option to make Glowing Compression Tools?

Example from Sellwand Plugin:

tier_1:
    name: "&6&lTier 1 Sell Wand"
    material: wooden_hoe
    glowing: true
    multiplier: 1.0
    uses: 50
    lore:
      - "&6Right-Click &eon chest to"
      - "&esell his content!"
      - ""
      - "&eSell wand information:"
      - "&e Multiplier: &6%multiplier%x"
      - "&e Uses: &6%uses%"
      - ""
      - "&eStatistics:"
      - "&e Total item sold: &6%total_item%"
      - "&e Total sold price: &6%total_sold_price%&e$"

**Comment by SirBlobman** [comment]
Thank you for the suggestion, I'll add glowing in a future update.

**Comment by SirBlazzit** [comment]
Awesome! 👍
