### ISSUE TITLE
Feature Request - Multiple Compression Tool Tiers

### ISSUE THREAD

**Issue by SirBlazzit** [SirBlobman/Block-Compressor#2]
Most sellwand plugins have multiple tiers with different use counts.
Would it be possible to add that for the Compression Tools via config?

Example from Sellwand Plugin:

tier_1:
    name: "&6&lTier 1 Sell Wand"
    material: wooden_hoe
    glowing: true
    multiplier: 1.0
    uses: 50
    lore:
      - "&6Right-Click &eon chest to"
      - "&esell his content!"
      - ""
      - "&eSell wand information:"
      - "&e Multiplier: &6%multiplier%x"
      - "&e Uses: &6%uses%"
      - ""
      - "&eStatistics:"
      - "&e Total item sold: &6%total_item%"
      - "&e Total sold price: &6%total_sold_price%&e$"

**Comment by SirBlobman** [comment]
I'm not sure I understand how a tier system would be useful. Sell wands for example can multiply prices and do other things, but the compressor tool just turns ingots/gems into blocks.

**Comment by SirBlazzit** [comment]
> I'm not sure I understand how a tier system would be useful.

Example:
Tier 1 would only have 10 uses
Tier 2 would have 50 uses
Tier 3 would have 100 and so on
Tier 4 would have 250
Tier 5 would have infinite uses
 
It would ideally allow people to add their own tiers if they wanted and makes the plugin more customizable, or they could keep it as a single tier.
